### ISSUE TITLE
Document affirmation for multiple authors

### ISSUE THREAD

**Issue by koppor** [latextemplates/scientific-thesis-cover#19]
How does it work with "Fachstudien"? Does one need to do something like the following?

    \makeatother
    \gdef\@AffirmationText{%
        Wir versicheren, diese Arbeit selbstständig verfasst zu haben.
        Wir haben keine anderen als die angegebenen Quellen benutzt und alle wörtlich oder sinngemäß aus anderen Werken übernommene Aussagen als solche gekennzeichnet.
        Weder diese Arbeit noch wesentliche Teile daraus waren bisher Gegenstand eines anderen Prüfungsverfahrens.
        Wir haben diese Arbeit bisher weder teilweise noch vollständig veröffentlicht.
        Das elektronische Exemplar stimmt mit allen eingereichten Exemplaren überein.
    }
    \makeatletter

**Comment by kmindi** [comment]
Is there an official "group" version for the affirmation text? Not that we introduce our own which is not signed off by the University.

For the implementation part, I can look into that in a few days. Is it possible to have three separate pages with the affirmation for each student his/her own?:
```
\Affirmation % for student 1
\Affirmation % for student 2
\Affirmation % for student 3
```

**Comment by chriba** [comment]
This issue can be closed now!
