### ISSUE TITLE
Visus institute is missing

### ISSUE THREAD

**Issue by moritz-h** [latextemplates/scientific-thesis-cover#20]
In the Readme file visus is listed as one of the institute options `institute=visus`, but it is not defined in the .sty file.

**Comment by koppor** [comment]
Please check with your supervisor. According to Ms. Ritzmann, works belongig to VISUS are organizationally belonging to VIS. See comment of commit https://github.com/latextemplates/scientific-thesis-cover/commit/64e731dd74e6bb01d23cf4deaee105ed2ec80b79.

I removed it from the README.md.

Feel free to open a pull request adding VISUS if you think the [Prüfungsausschuss Informatik](https://www.informatik.uni-stuttgart.de/fachbereich/gremien/pruefungsausschuesse/PA_Inf/index.html) got it wrong.
