### ISSUE TITLE
Cover Page Insitutes outdated?

### ISSUE THREAD

**Issue by PawelWojcik95** [latextemplates/scientific-thesis-cover#33]
Hello,

I think the ReadMe is not up-to-date when it comes to the institutes, is that possible?

I need a title page for the Institue of Software Engineering. 

When looking into your ReadMe, it says 

> institute=iste will state Institute of Software Engineering

However, when I put "iste" into my LateX file, I instead get the Institute of Software Technology in my compiled file. I am not sure, but that might be actually the old name for the institue. Is it possible to fix/add the desired ISTE ? 

Thanks

**Comment by Vogel612** [comment]
that change may not have been released to ctan yet. It was introduced in #32. If you get the `sty` file from `master` it should work as desired.

**Comment by PawelWojcik95** [comment]
> that change may not have been released to ctan yet. It was introduced in #32. If you get the `sty` file from `master` it should work as desired.

Thanks, this indeed already solved my issue.
